/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author lucas
 */
public class PanelMoldel extends javax.swing.JPanel {

    /**
     * Creates new form PanelMoldel
     */
    public PanelMoldel(String nome) {
        initComponents();
        insereTexto(nome);
        centralizaJPANE();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTitulo = new javax.swing.JLabel();
        btnOpen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(398, 174));
        setMinimumSize(new java.awt.Dimension(398, 174));
        setLayout(new java.awt.BorderLayout());

        txtTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("TITULO DO PDF");
        add(txtTitulo, java.awt.BorderLayout.PAGE_START);

        btnOpen.setText("OPEN");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        add(btnOpen, java.awt.BorderLayout.PAGE_END);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + "C:\\Users\\lucas\\Desktop\\Prova2.pdf");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Check file details");
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void insereTexto (String nome) {
        txtTitulo.setText(nome);
    }
    
    private void centralizaJPANE () {
        txtDescricao.setLineWrap(true);
        txtDescricao.setWrapStyleWord(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
